### PR TITLE
Addressing TODOs

### PR DESCRIPTION
**Pull request by shurymury**
This completes the work on CODETOOLS-7903274.
Remaining are updates to data coverage plugin.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jcov pull/38/head:pull/38` \
`$ git checkout pull/38`

Update a local copy of the PR: \
`$ git checkout pull/38` \
`$ git pull https://git.openjdk.org/jcov pull/38/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 38`

View PR using the GUI difftool: \
`$ git pr show -t 38`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jcov/pull/38.diff">https://git.openjdk.org/jcov/pull/38.diff</a>

</details>

### CODE REVIEW

**Comment by lkuskov** [comment]
LGTM, but! one thing which isn't in your TODO list - write descriptions for public classes that wouldn't be removed to highlight their usage and functionality.

**Comment by shurymury** [comment]
> LGTM, but! one thing which isn't in your TODO list - write descriptions for public classes that wouldn't be removed to highlight their usage and functionality.

You mean the javadoc? Of course that would be very useful.

**Comment by lkuskov** [comment]
Of course  the javadoc is appreciated to be in the reviewed code

**Pull request closed without merging**
