### PR TITLE
7903794: Allow to specify a zip file as an output

### PR DESCRIPTION
**Pull request by shurymury**
See this for documentation changes: https://bugs.openjdk.org/browse/CODETOOLS-7903795

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [CODETOOLS-7903794](https://bugs.openjdk.org/browse/CODETOOLS-7903794): Allow to specify a zip file as an output (**Sub-task** - P3)

### Reviewers
 * [Dmitry Bessonov](https://openjdk.org/census#dbessono) (@dbessono - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jcov.git pull/46/head:pull/46` \
`$ git checkout pull/46`

Update a local copy of the PR: \
`$ git checkout pull/46` \
`$ git pull https://git.openjdk.org/jcov.git pull/46/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 46`

View PR using the GUI difftool: \
`$ git pr show -t 46`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jcov/pull/46.diff">https://git.openjdk.org/jcov/pull/46.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jcov/pull/46#issuecomment-2299807229)

### CODE REVIEW

**Comment by shurymury** [comment]
@lkuskov Can you take a look?

**Review by dbessono — APPROVED** [review]

**Pull request closed without merging**
